# Generated by Django 5.0.7 on 2026-08-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bungalow_id', models.PositiveBigIntegerField()),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_code', models.CharField(max_length=50)),
                ('bungalow_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('total_guests', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BungalowImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=191, null=True)),
                ('is_primary', models.IntegerField()),
                ('sort_order', models.IntegerField()),
            ],
            options={
                'db_table': 'bungalow_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bungalows',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('slug', models.CharField(max_length=191, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
                ('daily_status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bungalows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('key', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expiration', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cache',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CacheLocks',
            fields=[
                ('key', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=191)),
                ('expiration', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cache_locks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FailedJobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=191, unique=True)),
                ('connection', models.CharField(max_length=191)),
                ('queue', models.CharField(max_length=191)),
                ('payload', models.TextField()),
                ('exception', models.TextField()),
                ('failed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'failed_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Galleries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=191, null=True)),
                ('file_path', models.CharField(blank=True, max_length=191, null=True)),
                ('video_url', models.CharField(blank=True, max_length=191, null=True)),
                ('type', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'galleries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobBatches',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('total_jobs', models.IntegerField()),
                ('pending_jobs', models.IntegerField()),
                ('failed_jobs', models.IntegerField()),
                ('failed_job_ids', models.TextField()),
                ('options', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.IntegerField(blank=True, null=True)),
                ('created_at', models.IntegerField()),
                ('finished_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('queue', models.CharField(max_length=191)),
                ('payload', models.TextField()),
                ('attempts', models.PositiveSmallIntegerField()),
                ('reserved_at', models.PositiveIntegerField(blank=True, null=True)),
                ('available_at', models.PositiveIntegerField()),
                ('created_at', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('slug', models.CharField(max_length=191, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(blank=True, max_length=191, null=True)),
                ('type', models.CharField(max_length=5)),
                ('category', models.CharField(blank=True, max_length=191, null=True)),
                ('status', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration', models.CharField(max_length=191)),
                ('batch', models.IntegerField()),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotorbikeBookings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_code', models.CharField(max_length=50)),
                ('customer_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('motorbike_id', models.PositiveBigIntegerField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'motorbike_bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motorbikes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('license_plate', models.CharField(blank=True, max_length=191, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('daily_status', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'motorbikes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetTokens',
            fields=[
                ('email', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalAccessTokens',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tokenable_type', models.CharField(max_length=191)),
                ('tokenable_id', models.PositiveBigIntegerField()),
                ('name', models.TextField()),
                ('token', models.CharField(max_length=64, unique=True)),
                ('abilities', models.TextField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personal_access_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('payload', models.TextField()),
                ('last_activity', models.IntegerField()),
            ],
            options={
                'db_table': 'sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('email', models.CharField(max_length=191, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=191)),
                ('role', models.CharField(max_length=12)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
