# Generated by Django 5.0.7 on 2026-08-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bungalows',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='motorbikes',
            options={'managed': True},
        ),
    ]
