# Generated by Django 5.0.7 on 2026-08-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bungalows_options_alter_motorbikes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='motorbikes',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='motorbikes/'),
        ),
        migrations.AlterField(
            model_name='bungalows',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='bungalows/'),
        ),
    ]
