# Generated by Django 5.0.7 on 2026-08-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_menuitems_options_motorbikes_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_code', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_number', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('items', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'food_orders',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='image',
            field=models.ImageField(blank=True, max_length=191, null=True, upload_to='menu_items/'),
        ),
    ]
