# Generated by Django 6.1 on 2026-08-13 10:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phòng')),
                ('room_type', models.CharField(choices=[('SINGLE', 'Phòng Đơn'), ('DOUBLE', 'Phòng Đôi'), ('FAMILY', 'Phòng Gia Đình'), ('BUNGALOW', 'Bungalow Gỗ'), ('VILLA', 'Villa Ven Hồ')], default='DOUBLE', max_length=20, verbose_name='Loại phòng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá phòng (VNĐ/đêm)')),
                ('capacity', models.IntegerField(default=2, verbose_name='Sức chứa (người)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='Link hình ảnh')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Sẵn sàng'), ('MAINTENANCE', 'Bảo trì')], default='AVAILABLE', max_length=20, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Danh sách phòng',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('FOOD', 'Món ăn'), ('DRINK', 'Thức uống'), ('MOTORBIKE', 'Thuê xe máy')], max_length=20, verbose_name='Loại dịch vụ')),
                ('name', models.CharField(max_length=100, verbose_name='Tên dịch vụ')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá (VNĐ)')),
                ('unit', models.CharField(default='phần', max_length=50, verbose_name='Đơn tính')),
                ('is_available', models.BooleanField(default=True, verbose_name='Đang phục vụ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả dịch vụ')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='Link hình ảnh')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Danh sách dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('ADMIN', 'Quản trị viên')], default='CUSTOMER', max_length=20, verbose_name='Vai trò')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Danh sách người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=32, unique=True, verbose_name='Mã đặt phòng')),
                ('check_in_date', models.DateField(verbose_name='Ngày nhận phòng')),
                ('check_out_date', models.DateField(verbose_name='Ngày trả phòng')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền (VNĐ)')),
                ('payment_status', models.CharField(choices=[('PENDING_PAYMENT', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy')], default='PENDING_PAYMENT', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú thêm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.room', verbose_name='Phòng đặt')),
            ],
            options={
                'verbose_name': 'Đơn đặt phòng',
                'verbose_name_plural': 'Danh sách đặt phòng',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Đánh giá (1-5 sao)')),
                ('comment', models.TextField(verbose_name='Nội dung đánh giá')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã bị ẩn (Bởi Admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.booking', verbose_name='Mã đơn đặt phòng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.room', verbose_name='Phòng')),
            ],
            options={
                'verbose_name': 'Đánh giá (Review)',
                'verbose_name_plural': 'Quản lý Đánh giá',
            },
        ),
        migrations.CreateModel(
            name='BookingServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Thành tiền (VNĐ)')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_detail', to='core.booking', verbose_name='Đơn đặt phòng')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Dịch vụ chọn')),
            ],
            options={
                'verbose_name': 'Chi tiết dịch vụ đi kèm',
                'verbose_name_plural': 'Chi tiết dịch vụ đi kèm',
            },
        ),
    ]
